### ISSUE TITLE
Flow typedef doesn't work?

### ISSUE THREAD

**Issue by ajhyndman** [facebookincubator/idx#30]
https://github.com/facebookincubator/idx/blob/master/packages/idx/src/idx.js.flow#L12

Is there a version of flow which comes with this type baked in?  For open-source users, it'd be nice if the distributed typedef was useful.

**Comment by zertosh** [comment]
`$Facebookism$Idx` is already baked into Flow. The `idx.js.flow` is just a convenience wrapper around it so that you automatically get it when you do `import idx from 'idx';`.

See https://flow.org/try/#0CYUwxgNghgTiAEA3W8CWwAeAueASAYlGCAEYD2ZA1qgM4C2uAkpgNwBQbALgJ4AOCAVRogY8ALzwA3m3jwArsJg4A-NNmyAdlDogcNTjFQaA5gBoZ6gGaGQG4DRUBBGDCjcAPEJEA+c7IC+bP7sbKCQsAjIorwwZLwO8F4wIWBkGvrwWjriaJgAFDFxNKbwAPri3mUAdAoiVVkgAJQheQ16BkbGzRyt2rrwyvqGJt1AA

**Comment by yungsters** [comment]
Versions of Flow starting with the one that was release when `idx` was initially made available to the public should all support `$Facebookism$Idx`.

**Comment by ajhyndman** [comment]
Oh wow, it's built into flow?  Thanks for the explanation.
